kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: {{ template "k8s-ldap.name" . }}
    chart: {{ template "k8s-ldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.loginapp.name }}
  name: {{ .Release.Name }}-ca
data:
  ca.pem: |
{{ .Values.loginapp.issuerCA | indent 4 }}
